# topic param
lane_cmd_topic: "/lane_cmd"
laser_cmd_topic: "/laser_cmd"
cmd_topic: "/cmd_vel"
traffic_data_topic: "/traffic_data_topic"

# speed param
speed_adjust_step: 0.001
speed_lowerbound: 0.05
speed_upperbound: 0.1

# threshold
lost_laser_threshold: 5
lost_lane_threshold: 5
get_laser_threshold: 3
