traffic_data_topic: "/traffic_data_topic"
model_file: "/home/pi/autodrive_ws/src/yolov5/asset/best-opt.bin"
param_file: "/home/pi/autodrive_ws/src/yolov5/asset/best-opt.param"
videoPath: "/dev/video10"
isDebug: false
